# Generated by Django 4.1 on 2025-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('reference_price', models.IntegerField(blank=True, null=True)),
                ('jd_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ram',
            },
        ),
    ]
