# Generated by Django 4.1 on 2025-03-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('reference_price', models.IntegerField(blank=True, null=True)),
                ('jd_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gpu',
            },
        ),
    ]
