# Generated by Django 4.1 on 2025-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_gpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('reference_price', models.IntegerField(blank=True, null=True)),
                ('jd_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cpu',
            },
        ),
    ]
