# Generated by Django 4.1 on 2025-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('reference_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='参考价')),
                ('jd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='京东价')),
                ('jd_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='京东链接')),
                ('product_image', models.URLField(default='https://example.com/default.jpg', max_length=500, verbose_name='产品图片')),
                ('product_parameters', models.TextField(blank=True, null=True, verbose_name='产品参数')),
            ],
            options={
                'verbose_name': '散热器',
                'verbose_name_plural': '散热器',
                'db_table': 'coolers',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('reference_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='参考价')),
                ('jd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='京东价')),
                ('jd_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='京东链接')),
                ('product_image', models.URLField(default='https://example.com/default.jpg', max_length=500, verbose_name='产品图片')),
                ('product_parameters', models.TextField(blank=True, null=True, verbose_name='产品参数')),
            ],
            options={
                'verbose_name': '主板',
                'verbose_name_plural': '主板',
                'db_table': 'motherboards',
            },
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('reference_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='参考价')),
                ('jd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='京东价')),
                ('jd_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='京东链接')),
                ('product_image', models.URLField(default='https://example.com/default.jpg', max_length=500, verbose_name='产品图片')),
                ('product_parameters', models.TextField(blank=True, null=True, verbose_name='产品参数')),
            ],
            options={
                'verbose_name': '电源',
                'verbose_name_plural': '电源',
                'db_table': 'power_supplies',
            },
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('reference_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='参考价')),
                ('jd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='京东价')),
                ('jd_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='京东链接')),
                ('product_image', models.URLField(default='https://example.com/default.jpg', max_length=500, verbose_name='产品图片')),
                ('product_parameters', models.TextField(blank=True, null=True, verbose_name='产品参数')),
            ],
            options={
                'verbose_name': '固态硬盘',
                'verbose_name_plural': '固态硬盘',
                'db_table': 'ssds',
            },
        ),
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'CPU', 'verbose_name_plural': 'CPU'},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'verbose_name': '显卡', 'verbose_name_plural': '显卡'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': '内存', 'verbose_name_plural': '内存'},
        ),
        migrations.AddField(
            model_name='cpu',
            name='jd_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='京东链接'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='product_image',
            field=models.URLField(default='https://example.com/default.jpg', max_length=500, verbose_name='产品图片'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='product_parameters',
            field=models.TextField(blank=True, null=True, verbose_name='产品参数'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='jd_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='京东链接'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='product_image',
            field=models.URLField(default='https://example.com/default.jpg', max_length=500, verbose_name='产品图片'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='product_parameters',
            field=models.TextField(blank=True, null=True, verbose_name='产品参数'),
        ),
        migrations.AddField(
            model_name='ram',
            name='jd_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='京东链接'),
        ),
        migrations.AddField(
            model_name='ram',
            name='product_image',
            field=models.URLField(default='https://example.com/default.jpg', max_length=500, verbose_name='产品图片'),
        ),
        migrations.AddField(
            model_name='ram',
            name='product_parameters',
            field=models.TextField(blank=True, null=True, verbose_name='产品参数'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='jd_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='京东价'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='reference_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='参考价'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='jd_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='京东价'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='reference_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='参考价'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='jd_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='京东价'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='reference_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='参考价'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterModelTable(
            name='cpu',
            table='cpus',
        ),
        migrations.AlterModelTable(
            name='gpu',
            table='gpus',
        ),
    ]
