# Generated by Django 4.1 on 2025-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_cooler_motherboard_powersupply_ssd_alter_cpu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('reference_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='参考价')),
                ('jd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='京东价')),
                ('jd_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='京东链接')),
                ('product_image', models.URLField(default='https://example.com/default.jpg', max_length=500, verbose_name='产品图片')),
                ('product_parameters', models.TextField(blank=True, null=True, verbose_name='产品参数')),
            ],
            options={
                'verbose_name': '机箱',
                'verbose_name_plural': '机箱',
                'db_table': 'cases',
            },
        ),
    ]
