# Generated by Django 4.1 on 2025-04-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
