# Generated by Django 4.1 on 2025-04-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_motherboard_audio_chip_motherboard_chipset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssd',
            name='cache',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='缓存'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='存储容量'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='interface',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='接口类型'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='mtbf',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='平均无故障时间'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='read_speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='读取速度'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='seek_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='平均寻道时间'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='硬盘尺寸'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='write_speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='写入速度'),
        ),
    ]
