# Generated by Django 4.1 on 2025-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_ssd_cache_ssd_capacity_ssd_interface_ssd_mtbf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='内存容量'),
        ),
        migrations.AddField(
            model_name='ram',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='内存主频'),
        ),
        migrations.AddField(
            model_name='ram',
            name='memory_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='内存类型'),
        ),
        migrations.AddField(
            model_name='ram',
            name='suitable_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='适用类型'),
        ),
        migrations.AlterModelTable(
            name='ram',
            table='rams',
        ),
    ]
