# Generated by Django 4.1 on 2025-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_ram_capacity_ram_frequency_ram_memory_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powersupply',
            name='cable_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出线类型'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='efficiency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='转换效率'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='hdd_connector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='硬盘接口'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='max_power',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='最大功率'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='motherboard_connector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主板接口'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='pfc_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PFC类型'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='psu_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电源类型'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='rated_power',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='额定功率'),
        ),
    ]
