# Generated by Django 4.1 on 2025-04-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_powersupply_cable_type_powersupply_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='api_support',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3D API'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='chip_manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='芯片厂商'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='chip_series',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='显示芯片系列'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='cooling',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='散热方式'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='core_clock',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='核心频率'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='core_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='核心代号'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='cuda_cores',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CUDA核心'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='design',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='显卡设计'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品尺寸'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_chip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='显卡芯片'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='gpu_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='显卡类型'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='interface_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='接口类型'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='io_ports',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='I/O接口'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='max_resolution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='最大分辨率'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_bandwidth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='内存带宽'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_bus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='显存位宽'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_clock',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='显存频率'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='显存容量'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='显存类型'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品型号'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='power_connectors',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='电源接口'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='process_tech',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='制作工艺'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='recommended_psu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='建议电源'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='stream_processors',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='流处理单元'),
        ),
    ]
