# Generated by Django 4.1 on 2025-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0016_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='comment_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='jd_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='京东店铺'),
        ),
    ]
