# Generated by Django 4.1 on 2025-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0017_cpu_comment_count_cpu_jd_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='comment_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='chassis',
            name='jd_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='京东店铺'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='comment_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='jd_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='京东店铺'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='comment_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='jd_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='京东店铺'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='comment_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='jd_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='京东店铺'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='comment_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='jd_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='京东店铺'),
        ),
        migrations.AddField(
            model_name='ram',
            name='comment_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='ram',
            name='jd_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='京东店铺'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='comment_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='jd_store',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='京东店铺'),
        ),
    ]
