# Generated by Django 4.1 on 2025-04-16 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0018_chassis_comment_count_chassis_jd_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='价格（元）')),
                ('date', models.DateField(verbose_name='记录日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='analyzer.cpu', verbose_name='关联CPU')),
            ],
            options={
                'verbose_name': 'CPU历史价格',
                'verbose_name_plural': 'CPU历史价格',
                'db_table': 'cpu_price_history',
                'ordering': ['-date'],
                'unique_together': {('cpu', 'date')},
            },
        ),
    ]
