# Generated by Django 4.1 on 2025-04-23 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0020_cpu_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='之前价格')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前价格')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('method', models.CharField(choices=[('email', '邮件'), ('sms', '短信')], default='email', max_length=20, verbose_name='通知方式')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='analyzer.favorite', verbose_name='收藏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '降价提醒',
                'verbose_name_plural': '降价提醒',
            },
        ),
    ]
