# Generated by Django 4.1 on 2025-04-24 06:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0022_ram_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAMPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='价格（元）')),
                ('date', models.DateField(verbose_name='记录日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='analyzer.ram', verbose_name='关联内存')),
            ],
            options={
                'verbose_name': '内存历史价格',
                'verbose_name_plural': '内存历史价格',
                'db_table': 'ram_price_history',
                'ordering': ['-date'],
                'unique_together': {('ram', 'date')},
            },
        ),
    ]
