# Generated by Django 4.1 on 2025-04-24 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0024_pricechangenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricechangenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pricechangenotification',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='analyzer_pr_user_id_0439b0_idx'),
        ),
    ]
