# Generated by Django 4.1 on 2025-04-25 05:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0025_alter_pricechangenotification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssd',
            name='product_id',
            field=models.CharField(default=1, help_text='从京东URL提取的SKU或自定义唯一ID', max_length=50, verbose_name='产品ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SSDPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='价格（元）')),
                ('date', models.DateField(verbose_name='记录日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('ssd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='analyzer.ssd', verbose_name='关联SSD')),
            ],
            options={
                'verbose_name': 'SSD历史价格',
                'verbose_name_plural': 'SSD历史价格',
                'db_table': 'ssd_price_history',
                'ordering': ['-date'],
                'unique_together': {('ssd', 'date')},
            },
        ),
    ]
