# Generated by Django 4.1 on 2025-04-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0026_ssd_product_id_ssdpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='product_id',
            field=models.CharField(default=1, help_text='从京东URL提取的SKU或自定义唯一ID', max_length=50, verbose_name='产品ID'),
            preserve_default=False,
        ),
    ]
