# Generated by Django 4.1 on 2025-04-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0031_cooler_product_id_coolerpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='product_id',
            field=models.CharField(default=1, help_text='从京东URL提取的SKU或自定义唯一ID', max_length=50, unique=True, verbose_name='产品ID'),
            preserve_default=False,
        ),
    ]
